repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: trailing-whitespace
    -   id: trailing-whitespace
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: '5.9.3'  # Use the sha / tag you want to point at
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: '21.9b0'  # Use the sha / tag you want to point at
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
