name: CS555
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - loguru
  - pip
  - pymongo
  - python=3.8
  - python-dateutil
  - regex
  - setuptools
  - pre-commit
  - PTable
  - pytest-cov
  - date_diff_calculator.py
  - ErrorLogger.py
  - family.py
  - individual.py
  - family_relationships.py
  - pip:
    - pyinputplus
    - pysimplevalidate
    - virtualenv==20.0.33
